[project]
name = "PyBCA"
version = "0.1.0"
description = "Brownian Cellular Automaton"
authors = [{ name = "Minamium", email = "arcadia.battery@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "torch>=2.0",
  "scipy"
]