title: PyBCA
description: PyBCA docs / Brownian Circuit Language (BCL)
remote_theme: just-the-docs/just-the-docs

# オプション（安全なものだけ）
search_enabled: true
color_scheme: nil   # 必要なら "dark"
aux_links:
  "GitHub": https://github.com/Minamium/PyBCA
aux_links_new_tab: true
